name: main

on:
  push:
    branches: main

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      latest: true
      push: true